### PR TITLE
Refactor: Use FillBytes() for zero padding instead of string formatting

### PR DESCRIPTION
**Pull request by ottosch**
- Rename PubKeyHash to PubKey in extractPubKeyHashFromP2TR;

### CODE REVIEW

**Comment by setavenger** [comment]
Thanks good catch!

I can merge it right away, alternatively you interested in making the change [here](https://github.com/setavenger/go-bip352/blob/d4f736816bcdc0f0e9d75ac4f1c8dc41336fd868/util.go#L81) and using the [go-bip352](https://github.com/setavenger/go-bip352) functions instead? I'm planning to replace most of this stuff with [go-bip352](https://github.com/setavenger/go-bip352). This could be the start of it. go-bip352 is better tested and more focused. It will also get the performance boosts once libsecp256k1 has full support for silent payments.

**Comment by ottosch** [comment]
Sure, will do.
Is it correct to do `go get github.com/setavenger/go-bip352`? I see that changes many dependencies versions in `go.mod/sum`.

**Comment by setavenger** [comment]
> Is it correct to do `go get github.com/setavenger/go-bip352`? I see that changes many dependencies versions in `go.mod/sum`.

Should be the way yes. Do you think it will break something? go-bip352 was created a couple months after the initial setup I did for oracle. This might be the reason for the version differences. 

I will also create an `integrate_go_bip352` branch against which you can open partial PRs if you want. Once everything is on go-bip352 we can merge that one into master.

**Comment by ottosch** [comment]
Ok, I updated the PR here and created one for go-bip352.
I think it's ok, was just wary of breaking things :)

**Comment by setavenger** [comment]
Cool works fine! 
I'll merge this into the interim branch. On a further scale though replacing the tweak computations etc. with go-bip352 should probably go hand in hand with replacing hashes which are currently strings with fixed size byte arrays as done in blindbitd and go-bip352. then we can also directly use the summing function available in go-bip352 and don't need to do what we are doing here.

**Pull request merged**
